// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bazphlbvqedefqujpimj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhenBobGJ2cWVkZWZxdWpwaW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NTc4MDEsImV4cCI6MjA3NzQzMzgwMX0.S8xnrR7v1RyYlB9qLPM8HP1q1R_S-G7mdBSKkzHtaMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});